import type { EnemyTier } from '../lib/types'

/*
  Story Mode — a single tale, "Story I: The Long Way Round".

  A wanderer crosses twelve regions of a puzzle-world. Each region is a chapter
  with a short premise and three levels. The questions are NOT subject material —
  they're general-knowledge / lateral-thinking brain-teasers (geography, logic,
  wordplay, patterns, "how many…"), generated by the AI from the chapter theme.

  Progression: chapter N opens when N-1 is fully cleared; levels run in order
  inside a chapter. Progress persists via the shared topic_progress table with
  subject_id = STORY_ONE.id.
*/

export interface StoryLevel {
  id: string
  title: string
  tier: EnemyTier
}

export interface Chapter {
  id: string
  /** 0-based position in the tale. */
  index: number
  title: string
  premise: string
  levels: StoryLevel[]
}

export interface Story {
  id: string
  title: string
  tagline: string
  chapters: Chapter[]
}

const LEVEL_TIERS: EnemyTier[] = ['easy', 'medium', 'hard']

function chapter(
  index: number,
  title: string,
  premise: string,
  levelTitles: [string, string, string],
): Chapter {
  const id = `s1-c${index + 1}`
  return {
    id,
    index,
    title,
    premise,
    levels: levelTitles.map((t, i) => ({
      id: `${id}-${i + 1}`,
      title: t,
      tier: LEVEL_TIERS[i],
    })),
  }
}

export const STORY_ONE: Story = {
  id: 'story-1',
  title: 'Story I: The Long Way Round',
  tagline:
    'One traveller, twelve regions, and a different way of thinking waiting in each.',
  chapters: [
    chapter(
      0,
      'The Threshold Village',
      'Every long road starts at a small gate. The village elders test travellers with the oldest riddles — the kind a child can answer and a scholar overthinks.',
      ['The First Gate', 'Counting Sheep', "The Elder's Riddle"],
    ),
    chapter(
      1,
      "The Cartographer's Coast",
      'Salt air and a thousand unrolled maps. Here they only trust those who know the shape of the world.',
      ['Name the Sea', 'Border Lines', 'The Missing Capital'],
    ),
    chapter(
      2,
      'The Clockwork Bridge',
      'A bridge of gears that lowers only for those who can keep time. Days, months and turning years are its toll.',
      ['Days in the Turning', 'The Leap', 'What Comes Sunday'],
    ),
    chapter(
      3,
      'The Whispering Library',
      'Shelves that rearrange themselves by meaning. The librarian speaks only in puzzles of letters and words.',
      ['Hidden Words', 'The Anagram Door', 'One Letter Off'],
    ),
    chapter(
      4,
      'The Market of Halves',
      'Everything here is sold in parts. Haggle well, and mind your change.',
      ['Half of a Half', 'Fair Shares', "The Merchant's Change"],
    ),
    chapter(
      5,
      'The Hall of Mirrors',
      'Patterns repeat down every corridor. Find the rule and the far door opens.',
      ['What Comes Next', 'The Broken Sequence', 'Fold the Shape'],
    ),
    chapter(
      6,
      "The Logician's Gate",
      'Two guards, and only one tells the truth. Nothing past this point is as simply stated as it seems.',
      ['Knights and Knaves', 'If, Then, Therefore', 'The Only Door'],
    ),
    chapter(
      7,
      'The Observatory',
      'A dome open to the night. The astronomers weigh worlds and measure the impossibly far.',
      ['Order of Worlds', 'How Far the Light', 'Weighing the Moon'],
    ),
    chapter(
      8,
      'The Menagerie',
      'Cages of living questions. Every creature here is a fact you half-remember.',
      ['Legs and Wings', 'The Fastest Thing', 'Inside the Body'],
    ),
    chapter(
      9,
      'The Vault of Records',
      'A hall of the most, the largest and the oldest. Superlatives only.',
      ['Tallest and Longest', 'The Oldest Living', 'Deepest and Highest'],
    ),
    chapter(
      10,
      'The Crossroads of Choice',
      'Four roads, each a trick. The obvious answer is almost never the way through.',
      ['The Obvious Trap', 'Think Sideways', 'The Riddle with a Turn'],
    ),
    chapter(
      11,
      'The Summit',
      'The last climb. Every region you crossed sends one final question up the mountain.',
      ['The Long View', 'All Roads Meet', "Story's End"],
    ),
  ],
}

// --- lookups -------------------------------------------------------------

export const STORY_CHAPTER_COUNT = STORY_ONE.chapters.length

export const getChapter = (chapterId: string | undefined) =>
  STORY_ONE.chapters.find((c) => c.id === chapterId)

export function getStoryLevel(
  chapterId: string | undefined,
  levelId: string | undefined,
) {
  return getChapter(chapterId)?.levels.find((l) => l.id === levelId)
}
